### ISSUE TITLE
Diagonal DPad Bug

### ISSUE THREAD

**Issue by stevenfelix505** [woesss/JL-Mod#1]
**Build version:**
Latest
**Game version:**
Any
**Game resolution:**
Any
**Device model:**
ASUS T00I
**Android version:**
5.0
**Description of the issue:**
![Screenshot_2020-04-25-13-26-26](https://user-images.githubusercontent.com/57618009/80272971-8f280f00-86f8-11ea-9c4d-aa820df5d833.jpg)
Can you fix the ←↓ and ↓→ buttons?

**Comment by woesss** [comment]
Do they work correctly but are not displayed correctly? Or just swapped places?

**Comment by stevenfelix505** [comment]
Text/characters ←↓ and ↓→ are not displayed correctly.

**Comment by woesss** [comment]
On previous versions of original J2ME Loader (before 1.5.6), there was no such problem?  
Switching layouts (in game menu->"Switch keylayout") does not fix it?

**Comment by stevenfelix505** [comment]
It doesn't fixing the ←↓and↓→ buttons

**Comment by stevenfelix505** [comment]
![Screenshot_2020-04-26-13-00-06](https://user-images.githubusercontent.com/57618009/80299353-e47a2400-87bd-11ea-81c1-a9433c1b29b4.jpg)
Now I change the font and it shows diagonal DPad correctly.

**Comment by stevenfelix505** [comment]
I can close the issue from now.

**Comment by woesss** [comment]
Good - I suspected the problem was in the font.  
Was it a replaced font or stock from the official firmware?

**Comment by stevenfelix505** [comment]
Replaced font
