### ISSUE TITLE
Heli Strike Rendering Issues

### ISSUE THREAD

**Issue by kkp9199** [woesss/JL-Mod#11]
**Emulator version:**
JLMod_b073+MC_b097.apk

**Game version:**
Heli Strike v1.1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320

**Device:**
``(For example, Samsung Galaxy S7)``
Xiaomi MI9T Pro

**Android version:**
Android 10

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The backgrounds are not rendered. Only the 3D models are rendered.
![Screenshot_2020-08-28-11-12-52-859_ru woesss j2meloader](https://user-images.githubusercontent.com/55281166/91525735-cb29e580-e91f-11ea-8bdf-9f39df618d91.jpg)

**Comment by woesss** [comment]
There is no background on this screen.  
Here is a screenshot from Sony Ericsson's official SDK emulator:
![heli_strike_3d_SonyEricsson_JP8_240x320_1](https://user-images.githubusercontent.com/36137354/91841418-02b7cb00-ec5b-11ea-809c-26d85db0055f.png)  
It's identical.
