### ISSUE TITLE
Crashes + corrupted graphics MC3D

### ISSUE THREAD

**Issue by stranno** [woesss/JL-Mod#12]
**Build version:**

JL-Mod_0.74+MC_b098

**Game version:**

Pandora Tomorrow 3D 1.0.3

**Game resolution:**

176x220

**Device model:**

OnePlus 7 and Black Shark 2

**Android version:**

Android 10 (OP7) and Android 9 (BS2)

**Description of the issue:**

Hi woesss. I have two problems here with the new MC3D shading build.

Pandora Tomorrow 3D, maybe other games, crashes randomly after a few seconds/minutes. It could be related to that old input crashes of J2ME-Loader, where the emulator crashed when you click on two+ buttons at the same time. I'm not sure, could be related to any other thing. I added the log. This happens on both devices.

The other problem only happens with my Black Shark 2 running Android 9. Shaded/lightning areas are completely corrupted, with high bloom and repeating patterns. Only accelerated OpenGL rendering works in this phone, no surface, window or even software (yeah, weird). This problem doesn't happen, at all, in the OnePlus 7 running Android 10, OpenGL hardware rendering works flawlesly on this device (but still crashes).

Both phones have the same SOC :-/

[log.txt](https://github.com/woesss/JL-Mod/files/5184405/log.txt)

![Screenshot_20200908-020235](https://user-images.githubusercontent.com/6293197/92410746-60f61980-f145-11ea-9659-3c9f9a10f70c.png)

**Comment by woesss** [comment]
Try new version - crashes should stop

**Comment by stranno** [comment]
I have tried it a few times and seems stable, no crashes so far. Thank you so much.

Any idea about the graphics corruption on Black Shark 2? I guess it is something about the rom. BS2 is running a custom implementation of Xiaomi's MIUI, while OnePlus 7 is running LineageOS, OxygenOS (the OnePlus OS) worked fine too.

I'm running it out of the sandboxed Game space. No difference.

**Comment by woesss** [comment]
What version did it start with, or has it always been?  
Graphics modes other than OpenGL ES may not work because I replaced the wrapper class for OpenGL ES compatibility

**Comment by stranno** [comment]
The latest release: 0.74+MC_0.98.2.

**Comment by woesss** [comment]
I asked about problems on Black Shark - in which version of the emulator did they appear?

**Comment by stranno** [comment]
I have tried all versions and it seems it has been always broken, since b070+MC_b096, the first release with shaders support.

I didn't notice since OP7 is my main phone. I barely have used the BS2 for JL-Mod.

**Comment by stranno** [comment]
Hey woesss, I have seen your latest update and now it seems to work right! At least from I have tested.

Both problems seem to be resolved so closing this issue.

Thank you so much for your efforts.
