### ISSUE TITLE
MC3D Games Bug

### ISSUE THREAD

**Issue by stevenfelix505** [woesss/JL-Mod#13]
**Build version:**
Since 0.74+MC_b098 until 0.75+MC_0.98.2
**Game name, version, and resolution:**
Deep Abyss 3D v1.2 (240×320)
Honey Cave 3D v1.3 (176×220)
Hungry Puppy 3D v1.2.2 (176×220)
**Device model:**
Samsung SM-A105G
**Android version:**
10
**Description of the issue:**
The emeralds doesn't show :
![Screenshot_20200918-111621_JL-Mod](https://user-images.githubusercontent.com/57618009/93555946-b03c1580-f9a1-11ea-8472-d5ec1edb814d.jpg)
The bear doesn't show :
![Screenshot_20200918-111652_JL-Mod](https://user-images.githubusercontent.com/57618009/93556002-cd70e400-f9a1-11ea-9167-769be526c78e.jpg)
The tiles doesn't show :
![Screenshot_20200918-111732_JL-Mod](https://user-images.githubusercontent.com/57618009/93556043-e7aac200-f9a1-11ea-82af-7c4366c0ab7c.jpg)
Can you fix them all?

**Comment by woesss** [comment]
Save the logs immediately after entering the game scene and send me.

**Comment by stevenfelix505** [comment]
I have sent you the log file. Check your Discord.

**Comment by stevenfelix505** [comment]
The current solution after I talk to @woesss on Discord :
Download b073+MC_b097 version
