### ISSUE TITLE
A Floating, movable and editable action bar button!

### ISSUE THREAD

**Issue by UserXVI** [woesss/JL-Mod#15]
Thank you very much for improve this great app and maintain j2me games alive, but I have a suggestion,  the action bar is very useful, however due to the space it occupies on the screen, sometimes it messes up the buttons when it is activated, besides having to choose between full screen and the action bar, and it is necessary to close the application to make a small change in the keyboard layout, so I had a idea, a floating button that can be activated or deactivated that will not mess up the keyboard, will keep the screen full and can be moved anywhere on screen! 

With action bar:
![Screenshot_20210115-185129](https://user-images.githubusercontent.com/64711656/104786599-2001b780-576c-11eb-8640-0404b0e2eb4a.png)

Without action bar:
![Screenshot_20210115-185206](https://user-images.githubusercontent.com/64711656/104786645-40ca0d00-576c-11eb-9cee-df4078a22db3.png)

With a floating action bar button!
![PhotoGridLite_1610748878348](https://user-images.githubusercontent.com/64711656/104786682-5d664500-576c-11eb-9f5a-7aac428f1bba.jpg)

**Comment by woesss** [comment]
Menu button added to virtual keyboard. But it invisible by default for all layouts except 'phone'.
