### ISSUE TITLE
Installation menu error

### ISSUE THREAD

**Issue by RobertoR0** [woesss/JL-Mod#16]
**Build version:**
0.77.1+MC_0.98.4
**Game version:**

**Game resolution:**

**Device model:**
Samsung Galaxy J5 Pro
**Android version:**
9
**Description of the issue:**
After installing a game your information is hidden in portrait mode, when I change to landscape mode and return to portrait the imports appear.
![Screenshot_20210123-101133_JL-Mod](https://user-images.githubusercontent.com/36806488/105579470-9b172f00-5d65-11eb-9aa3-9132f1626677.jpg)
![Screenshot_20210123-101154_JL-Mod](https://user-images.githubusercontent.com/36806488/105579480-b7b36700-5d65-11eb-8c94-685506e19a7c.jpg)
![Screenshot_20210123-101205_JL-Mod](https://user-images.githubusercontent.com/36806488/105579493-da458000-5d65-11eb-9c4f-d7dd00e0927a.jpg)

**Comment by woesss** [comment]
Everytime? First installation or reinstallation/update, from an in-app file picker or from external applications, from JAD or JAR - does either of this matter, or is the window always blank?

**Comment by RobertoR0** [comment]
Yes every time, both for new installations and for reinstallations, it doesn't matter if the installation is through the internal or external file selector it always happens, but when I install a JAD through the internal file selector some information appears. I didn't bother with it, but I thought I could report this little display error :)

**Comment by woesss** [comment]
Latest build should fix this
