### ISSUE TITLE
White blank screen upon load in Bioshock and some other games.

### ISSUE THREAD

**Issue by DavidAriyan** [woesss/JL-Mod#17]
**Build version:** 0.77.1+MC_0.98.4

**Game version:** 1.1.3

**Game resolution:** 640x360

**Device model:** Sony Xperia XZ1

**Android version:** 9 Pie

**Description of the issue:**
Game failed to load and only show white blank screen. Same with other game by Indiagames.ltd John Carter. And these games too: Keto Adventure, Blood+ , Quantum of Solace.

Your mod app is really great. Please fix this as these games is good and is run in original j2meloader

**Comment by woesss** [comment]
I understood the reason - I will fix it

**Comment by DavidAriyan** [comment]
wow! that is super fast. Thank you Dev.
