### ISSUE TITLE
Galaxy on Fire 2 - Space Lounge Graphical Issue

### ISSUE THREAD

**Issue by Indra2108** [woesss/JL-Mod#18]
**Build version:**
0.77.2+MC_0.98.4

**Game version:**
1.0.3

**Game resolution:**
240x320

**Device model:**
Advan G9 Pro

**Android version:**
10

**Description of the issue:**
There is graphical issue when i enter the space lounge

Graphic Mode: Software
![Screenshot_20210212-201009](https://user-images.githubusercontent.com/47787767/107773913-ea52ed00-6d70-11eb-8749-13c364477979.png)

Graphic Mode: HW Acceleration (OpenGL ES)
![Screenshot_20210212-201722](https://user-images.githubusercontent.com/47787767/107774227-4d448400-6d71-11eb-9c75-90db16a95ca2.png)

Graphic Mode: HW Acceleration (window)
![Screenshot_20210212-201823](https://user-images.githubusercontent.com/47787767/107774458-9ac0f100-6d71-11eb-95d8-6bb680d9547a.png)

Graphic Mode: HW Acceleration (surface)
![Screenshot_20210212-201946](https://user-images.githubusercontent.com/47787767/107774544-b926ec80-6d71-11eb-9a52-6d46093af602.png)

**Comment by woesss** [comment]
Fixed

**Comment by Indra2108** [comment]
Thanks, it should be playable now.

![Screenshot_20210217-085030](https://user-images.githubusercontent.com/47787767/108145075-68125200-70fd-11eb-9d8e-b386293dd108.png)
