### ISSUE TITLE
3d object not rendered

### ISSUE THREAD

**Issue by ZackyC** [woesss/JL-Mod#19]
**Build version:**
JL-Mod_0.77.2+MC_0.98.4.
**Game version:**
(dakar 09)1.1.3 ; (dakar10)0.1.8
**Game resolution:**
240 x 320 pxl
**Device model:**
REDMI NOTE 8 GINKO
**Android version:**
9.0 PIE
**Description of the issue:**
3d object not rendered and cant choosing menu, overlapping text menu and stuck on selecting car, already trying using micro3d fix command for medal of honor, lowering fps, and change render graphics mode but still nothing help,
![Screenshot_dakar 09 240x320](https://user-images.githubusercontent.com/35026289/107845283-f12f3d80-6e0c-11eb-930e-079cab0f8849.png)
[log dakar 09 240x320.txt](https://github.com/woesss/JL-Mod/files/5975317/log.dakar.09.240x320.txt)

but for ea rally dakar 2010 it can play but has similiar bug

![Screenshot_dakar 10](https://user-images.githubusercontent.com/35026289/107845445-048ed880-6e0e-11eb-92b8-8529b9ccd62b.png)
[log dakar 10 240x320.txt](https://github.com/woesss/JL-Mod/files/5975323/log.dakar.10.240x320.txt)

download source dedomil.net

**Comment by woesss** [comment]
What specific versions have you tried?  
I checked all three games, versions for Sony Ericsson K800i - no bugs were found.

**Comment by woesss** [comment]
Fixed

**Comment by ZackyC** [comment]
thanks already fixed with latest updated apks build JL-Mod_0.77.3+MC_0.98.5
