### ISSUE TITLE
Stuck in loading

### ISSUE THREAD

**Issue by ZackyC** [woesss/JL-Mod#20]
**Build version:**
JL-Mod_0.77.2+MC_0.98.4.
**Game version:**
1.0.2
**Game resolution:**
240 x 320 pxl
**Device model:**
REDMI NOTE 8 GINKO
**Android version:**
9.0 PIE
**Description of the issue:**
Stuck on grid loading after in game briefings

![Screenshot_race driver grid 240x320](https://user-images.githubusercontent.com/35026289/107845683-f8a41600-6e0f-11eb-86ec-500906e9baad.png)
[log race driver grid 240x320.txt](https://github.com/woesss/JL-Mod/files/5975339/log.race.driver.grid.240x320.txt)

download source dedomil.net

**Comment by woesss** [comment]
Fixed

**Comment by ZackyC** [comment]
thanks already fixed with latest updated apks build JL-Mod_0.77.3+MC_0.98.5
