### ISSUE TITLE
Overlaping texture

### ISSUE THREAD

**Issue by ZackyC** [woesss/JL-Mod#21]
**Build version:**
JL-Mod_0.77.3+MC_0.98.5.
**Game version:**
1.0.9 Moded button version
**Game resolution:**
240 x 320 pxl
**Device model:**
REDMI NOTE 8 GINKGO
**Android version:**
9.0 PIE
**Description of the issue:**
Tenchu Ayames Tale Healtbar overlaping with ground texture, but working fine with vanila version (unmoded keymap)

when starting from beginig chapter
![Screnshot_Tenchu 240x320 (1)](https://user-images.githubusercontent.com/35026289/107905080-450e6380-6f80-11eb-88bb-5788c0a92ca4.png)

when little bit walking ground texture is overlaping with health bar
![Screnshot_Tenchu 240x320](https://user-images.githubusercontent.com/35026289/107905123-6bcc9a00-6f80-11eb-81cd-ac04fbf39732.png)

download source seclub.org

**Comment by woesss** [comment]
There is a bug in the SE SDK emulator and this version was built with this bug in mind. I have already encountered this problem with the example of "Resident Evil - The Missions". I'm not sure if this bug was on real phones - unfortunately I no longer have a working handset.

**Comment by ZackyC** [comment]
already trying with se emulator, bug only on happened with coliding object betwen character with environment ( walls, box) , but for health bar isn't happen? any possibilities to mapping button A and B for this games?

**Comment by ZackyC** [comment]
this is gameplay footage from 4 years ago on youtube, but i dont know if this playing with se emulator or real hardware but looks like still same games (moded keypad button assignment) 

https://m.youtube.com/watch?v=r0BmEUKhN58
