### ISSUE TITLE
not rendered

### ISSUE THREAD

**Issue by ZackyC** [woesss/JL-Mod#22]
**Build version:**
JL-Mod_0.77.3+MC_0.98.5.
**Game version:**
1.1.0 (both of them with terjef)
**Game resolution:**
176 x 220 pxl
**Device model:**
REDMI NOTE 8 GINKGO
**Android version:**
9.0 PIE
**Description of the issue:**
Roller Bot 3D is not rendered correctly, there are 2 version game but only one 
of them wiill crashing in game when acess emulator menus on top right screen also freezing when playing, already trying fixing with micro3d comand but still didnt fixed the bug,

![Screenshot_Rollerbot 176x220](https://user-images.githubusercontent.com/35026289/107907147-763d6280-6f85-11eb-8111-2ebc3be6b605.png)
[log rollerbot 176x220.txt](https://github.com/woesss/JL-Mod/files/5979573/log.rollerbot.176x220.txt)

download source seclub.org

**Comment by woesss** [comment]
This game does not use the miсro3d engine API correctly. If I tweak the implementation for this, the performance of all Mascot games will drop dramatically. The best way is to fix the game itself.

**Comment by ptnnx** [comment]
RollerBot 3D uses the MLJ3D! 😅
(I don't familiar with MLJ)
Here you can find more information!
https://web.archive.org/web/20090608092353/http://www.bit7.co.uk/mlj3d.html
