### ISSUE TITLE
freezing when start

### ISSUE THREAD

**Issue by ZackyC** [woesss/JL-Mod#25]
**Build version:**
JL-Mod_0.77.3+MC_0.98.5.
**Game version:**
1.3.0
**Game resolution:**
240 x 320 pxl
**Device model:**
REDMI NOTE 8 GINKGO
**Android version:**
9.0 PIE
**Description of the issue:**
Star Wars Imperial Ace 3D is not starting/freezing when booting the game on last build, but playable on old build 0.76.

[log Star Wars Imperial Ace 3D 240x320.txt](https://github.com/woesss/JL-Mod/files/5993363/log.Star.Wars.Imperial.Ace.3D.240x320.txt)

download source sefan.ru, mobiles24.co

**Comment by woesss** [comment]
Does the latest build fix this?
