### ISSUE TITLE
Clean stretch (integer scaling)

### ISSUE THREAD

**Issue by Jamirus238** [woesss/JL-Mod#26]
I'm using the latest release build.
Maybe this is already implemented in some way, but I just don't see how it is possible here. I'd like to stretch games cleanly by integers but the scaling option doesn't allow for 200%, 300% etc. I thought maybe it would work by entering size values manually (e.g. instead of 240x320 -> 720x960) but that doesn't scale the midlet size picture size, it just creates a window in that size.

**Comment by woesss** [comment]
Changed max scale to 1000% for "As is" scale type (max zoom x10)
