### ISSUE TITLE
Bug with Marble Madness 3D

### ISSUE THREAD

**Issue by sotirisdim4** [woesss/JL-Mod#29]
**Emulator version: 0.77.3+MC_0.98.5**

**Game version: Marble Madness 3D v1.7**

**Game resolution: 240x320**

**Device: Samsung Galaxy S10+ Exynos (SM-G975F)**

**Android version: 11 (Version G975FXXU9FUCD)**

**Description of the issue: When playing Marble Madness 3D, levels GOLD 1 and GOLD 2 play just fine, but in GOLD 3, the textures are jittery, and when you get past a certain point in the level, the 3D textures completely disappear, leaving only the backgroud visible (but the game behaves as if nothing is wrong). This happens even when the ``micro3d.v3.render.no-mix2D3D: true`` parameter is set, and no matter if I use a software or a hardware renderer. Also, changing the resolution does nothing either. Also, accelerometer functions don't work, and if you don't disable motion in the game settings menu, you can't even move around if you attempt to play a level, and the timer is frozen. Attached below are screenshots from GOLD 1, GOLD 3 before and after the point where the texture vanishing happens, and also my game settings.**

EDIT: Additionally, if you turn on landscape mode on in settings, and attempt to play any level, it outright refuses to load, getting stuck on the loading screen.

![Screenshot_20210504-210809_JL-Mod](https://user-images.githubusercontent.com/53342566/117051839-a9d78f80-ad1f-11eb-86b8-a8f9384267ea.png)
![Screenshot_20210504-211000_JL-Mod](https://user-images.githubusercontent.com/53342566/117051847-aa702600-ad1f-11eb-86a4-4979facfb94f.png)
![Screenshot_20210504-211022_JL-Mod](https://user-images.githubusercontent.com/53342566/117051849-aa702600-ad1f-11eb-83f0-f30c24709a33.png)
![Screenshot_20210504-211026_JL-Mod](https://user-images.githubusercontent.com/53342566/117051851-ab08bc80-ad1f-11eb-8817-78ee09d8f16d.png)
![Screenshot_20210504-211032_JL-Mod](https://user-images.githubusercontent.com/53342566/117051853-aba15300-ad1f-11eb-961b-c60f05233ace.png)
![Screenshot_20210504-211932_JL-Mod](https://user-images.githubusercontent.com/53342566/117051854-ac39e980-ad1f-11eb-943d-4c1082559204.png)
![Screenshot_20210504-211940_JL-Mod](https://user-images.githubusercontent.com/53342566/117051855-acd28000-ad1f-11eb-9882-c23677fa22f1.png)
![Screenshot_20210504-211946_JL-Mod](https://user-images.githubusercontent.com/53342566/117051856-ad6b1680-ad1f-11eb-8fbf-06353a9a75d0.png)
![Screenshot_20210504-211949_JL-Mod](https://user-images.githubusercontent.com/53342566/117051858-ae03ad00-ad1f-11eb-9d12-97306f5e455c.png)

**

**Comment by woesss** [comment]
Send me your save - I won't have the patience to go through even one level.  
Also, save the log immediately after starting GOLD3 and send it too.

**Comment by sotirisdim4** [comment]
> 
> 
> Send me your save - I won't have the patience to go through even one level.
> Also, save the log immediately after starting GOLD3 and send it too.
> 
> The problem with the accelerometer is complicated - there are differences in units of measurement for different phone models and they cannot be determined automatically. There are also differences in the implementation of the interface for working with the sensor. To solve this, we need to collect a database of phone configurations and implement emulation of specific models by choosing the appropriate profile. In this case, the user will have to know for which model the game was developed.

Here are the files you asked for. The bug keeps happening in the new version as well. Now as far as what phone the game was designed for, I'm not really sure. As far as I know it came included with the Sony Ericsson W910i but I've also seen it for the K850i so I'm not really sure.
[MM3D Save + GOLD3 Log.zip](https://github.com/woesss/JL-Mod/files/6562046/MM3D.Save.%2B.GOLD3.Log.zip)

**Comment by woesss** [comment]
A graphical bug has been fixed. Fixing the accelerometer requires more serious work.

**Comment by Moutoncorne** [comment]
Les jeux ne sont pas en français. J'aimerai que vous ajouter cette langue pour que je  comprenne mieux. Et j'aimerais beaucoup que vous améliorer les sons et musique des jeux pour que ce soit plus agréable à jouer. J'espère que vous lirez mon message

**Comment by woesss** [comment]
@Moutoncorne L'émulateur ne peut pas vous aider avec cela. Vous devez rechercher des jeux en français - la langue est alors sélectionnée dans les paramètres du jeu lui-même, ou automatiquement en fonction de la langue de votre appareil. Si vous n'êtes pas satisfait de la traduction dans l'interface de l'émulateur lui-même, vous pouvez aider à l'améliorer ici: https://crowdin.com/project/j2me-loader  
Je ne connais pas le français. Et s'il vous plaît ne postez pas la même chose sur tous les sujets à la fois.

**Comment by Moutoncorne** [comment]
For games, I went to dedomil but the sony ericsson k800I games are only in English. I'm not sure if there is a way to get the games in French?

**Comment by woesss** [comment]
Accelerometer support added

**Comment by GeorgeYT9769** [comment]
Yoo im looking for that game, but nowhere on the internet. Does anyone have it? Thx
