### ISSUE TITLE
Broken controls in the latest release

### ISSUE THREAD

**Issue by stranno** [woesss/JL-Mod#3]
Controls are broken in the b068+MC_b093 build.

Only L/R and 1/3/7/9 are working in most games. Every other button doesnt respond, no matter if virtual or mapped to a gamepad.

Regular J2ME-Loader works fine.

Thank you.

Note: I labeled it wrong, sorry.

**Comment by woesss** [comment]
Try new build [b069+MC_b093](https://github.com/woesss/JL-Mod/releases/tag/b069)
