### ISSUE TITLE
Bruce Lee - Iron First 3D [Freeze]

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#35]
**Build version:**
Latest
**Game version:**
1.1.2
**Game resolution:**
240x320
**Device model:**
Realme 7/8 pro
**Android version:**
Android 11
**Description of the issue:**
When i start playing game, freeze!
Dedomil version 1.1.2/1.5.7 doesn't work but phoneky version 1.1.3 work!
http://dedomil.net/games/3173/screens

Log;
[log.txt](https://github.com/woesss/JL-Mod/files/7774290/log.txt)

**Comment by woesss** [comment]
This game requires a system property:  
`microedition.platform: SonyEricssonW900i`  
And set the FPS limit to 30.  
The picture twitches a little, but you can play.

**Comment by Rdx-fork** [comment]
Thank you!
Now working 😀

**Comment by ptnnx** [comment]
Can we close this? If no other solution (without any settings)?

**Comment by ptnnx** [comment]
Fixed
