### ISSUE TITLE
3D Super ball - doesn't work

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#38]
**Build version:**
Latest
**Game version:**
1.3.1
**Game resolution:**
176x220
**Device model:**
Realme 7/8 pro
**Android version:**
11
**Description of the issue:**
Crash, doesn't work!

https://user-images.githubusercontent.com/81209454/147429401-8cb33dfa-cd06-4bae-961e-d651c406d9e2.mp4

DL:
[3DSB.jar.zip](https://github.com/woesss/JL-Mod/files/7778098/3DSB.jar.zip)

Log:
[log.txt](https://github.com/woesss/JL-Mod/files/7778095/log.txt)

**Comment by woesss** [comment]
This game requires a System Property:
`microedition.platform: SonyEricssonK750i`  
(You can change it at the very bottom of the settings window)

**Comment by Rdx-fork** [comment]
Appear white screen!

https://user-images.githubusercontent.com/81209454/147621147-a6601c30-d75d-413a-a3cc-c08ab25aef8b.mp4

**Comment by ptnnx** [comment]
Fixed
