### ISSUE TITLE
Fast and Furious Fugitive 3D

### ISSUE THREAD

**Issue by NightWolf2014** [woesss/JL-Mod#42]
Fast and Furious Fugitive 3D version doesn't work, still have the same inssues that exist in J2ME Loader, some times the garage doesn't load with the car model and some times load, but if i click to start a race, the game will get stuck and stop work.

**Comment by NightWolf2014** [comment]
I used JL Mod because all of Mascot Capsule 3D games doesn't work in J2ME
Loader. JL-Mod doesn't have Mascot Capsule 3D support? Because most of 3D
games with that system works, except Fast and Furious Fugitive.

Em Sex, 11 de fev de 2022 07:03, Rdx (a.k.a. ptnn) ***@***.***>
escreveu:

**Comment by ptnn0** [comment]
**_JL-Mod have Mascot Capsule 3D! support_**.

*Like woesss said :*
> the implementation is not complete, somewhere a curve, little tested.

..Also i tested this game, it doesn't work for me. Freeze when i start a race...after force closed!

**Comment by NightWolf2014** [comment]
When that implementation will be completed?

Em Sex, 11 de fev de 2022 10:36, Rdx (a.k.a. ptnn) ***@***.***>
escreveu:

**Comment by ptnn0** [comment]
IDK, woesss knows!

**Comment by NightWolf2014** [comment]
This inssue should be closed because the game was fixed.
