### ISSUE TITLE
The Latest Version Can't Access Files Even if I Manually Grant "Manage All Files"

### ISSUE THREAD

**Issue by keepChatAlive** [woesss/JL-Mod#47]
**Build version:** 0.82.1

**Game version:**Any

**Game resolution:** Any

**Device model:** OPPO K9S

**Android version:** 11

**Description of the issue:** App can't browse for game files even after I give the app "manage all files permission" manually in the popup window upon opening the app. The file browser is empty with the error message "Permission to access filesystem denied". It seems that the app does not ask for file permission in a particular way: It does not have the manage files permission in app settings. You can only give the permission through the special permission page (the popup window upon opening the app).

**Comment by ptnnx** [comment]
In latest version of JL-mod, file browser error/bug appear for me! (Previous build work! fine)

https://user-images.githubusercontent.com/81209454/171529510-d8819b1f-802c-4eef-a960-43f91bd2106e.mp4

**Comment by woesss** [comment]
Fixed
