### ISSUE TITLE
LocoRoco - Black screen bug?

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#48]
**Build version:**
Latest [0.82.2]
**Game version:**
0.85 - [Download](https://oldfag.top/downloads/?act=view&id=2413)
**Game resolution:**
240x320 [L]
**Device model:**
Realme 9 pro+ and 8 pro
**Android version:**
Android 12
**Description of the issue:**
In-game, whenever i press the left key, i get to see a black screen bug, I don't know if this is a bug or not?
As you can see in this video.

https://user-images.githubusercontent.com/81209454/172046901-7bde998d-069e-49b9-80e5-0e4f50e73d3b.mp4

But according to this video so yes! It's bug!
[YouTube Link](https://youtu.be/4OmMzK5A57k)

**Log**
[log.txt](https://github.com/woesss/JL-Mod/files/8839813/log.txt)

**Comment by woesss** [comment]
This is a trick. Big Lokko crumbles into several small ones and at the same time the sky blinks.  

I see Sample3D crashing in the logs - is it from some kind of SDK? This SDK would be useful to me.

**Comment by ptnnx** [comment]
Oh so that isn't bug, it's just trick😂.
Well, i have some MC3D resources include Sample3D (but exactly i don't remember it came from SDK)...well you can see! Here
[MC3D_resources](https://github.com/ptnnx/Mascot-Capsule-3D/releases/download/1.0/Resources.zip)
