### ISSUE TITLE
Real Boxing 3D - crash

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#50]
**Build version:**
Latest
**Game version:**
1.0.1 [R]
**Game resolution:**
176x220
**Device model:**
Realme 9 pro+
**Android version:**
12
**Description of the issue:**
When i play game immediately crash.

https://user-images.githubusercontent.com/81209454/172134496-f25f7d1f-1489-483d-a193-7dcbbb3b3bb3.mp4

**Log**
[log.txt](https://github.com/woesss/JL-Mod/files/8843316/log.txt)
**Crash log**
[crash.txt](https://github.com/woesss/JL-Mod/files/8843339/crash.txt)

**Comment by woesss** [comment]
It is necessary to limit the FPS.  
The problem due to too high speed of the game.

**Comment by ptnnx** [comment]
Oh, but game only work with 30fps limit otherwise  it will crash. 30fps is very slow speed🥺

**Comment by woesss** [comment]
Moreover, you need to choose the FPS that was on the target device - otherwise the animations do not work correctly (animation frames are designed for a certain frame rate).

**Comment by ptnnx** [comment]
Thank you!😀, I will do that!

**Comment by ptnnx** [comment]
Here JL-Mod compatibility list, I hope it will be useful for you.
[[Mascot Capsule 3D compatibility list](https://emulation.gametechwiki.com/index.php/Mascot_Capsule_3D_compatibility_list)
