### ISSUE TITLE
HOW: Nanowarrior - missing textures

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#51]
**Build version:**
Latest
**Game version:**
1.1.0 SE
**Game resolution:**
240x320
**Device model:**
Realme 9 pro+
**Android version:**
12
**Description of the issue:**
Missing textures!

https://user-images.githubusercontent.com/81209454/172137882-d5291501-8ed6-4db7-9e01-a8bc6347117b.mp4

**log**
[log.txt](https://github.com/woesss/JL-Mod/files/8843478/log.txt)

**Comment by woesss** [comment]
I do not understand - what textures are missing?  
I ran it on the SE WTK emulator - everything seems to look the same.

**Comment by ptnnx** [comment]
I saw pink dots on coconut tree. If am compare with Nokia version, there isn't pink dots on Nokia ver. Also sky and area is accurate on Nokia. 

I was confused when I compared the versions of Nokia and SE. So I thought it is texture problem but this game is from Mascot so looks different from nokia ver. My bad 😅 [Now you can close this issue]..

**Nokia (M3G)**
![IMG_20220607_122426](https://user-images.githubusercontent.com/81209454/172319648-d232ed1c-2dea-436c-9ef2-6d8af81dc2fe.jpg)

**SE (Mascot 3D)**
![IMG_20220607_122411](https://user-images.githubusercontent.com/81209454/172319752-9e6fd302-2a4f-402d-9853-cac9782a3269.jpg)
