### ISSUE TITLE
Few racing games crashing in latest JL-Mod

### ISSUE THREAD

**Issue by ptnnx** [woesss/JL-Mod#53]
* _Recently I noticed that most of the racing games are crashing in the latest JL-Mod version (work fine in previous 0.81 build)_

- **LOG**
[log.txt](https://github.com/woesss/JL-Mod/files/8885330/log.txt)

| Name | GVer | JL-ModVer | Status | Note |
|-----|-----|-----|-----|-----|
| **[Street Race World 3D](https://phoneky.com/games/?id=j4j22787)** | 1.23.9 [SE] | All | graphic not rendered (when starting a race, show a green screen) |
| **[Ridge Racer 3D](https://oldfag.top/downloads/?act=view&id=3297)** | 1.0.3 [SE] | All | graphic not rendered (cars) |
| **[The Sims Pool 3D](https://oldfag.top/downloads/?act=view&id=7844)** | 1.15.26 [SE] | All | crash | |

**Video**

https://user-images.githubusercontent.com/81209454/173220817-8de27343-8e8d-43d6-bee8-7ec8527fb842.mp4

**Comment by woesss** [comment]
Should work on a new build (requires reinstalling the game)

**Comment by ptnnx** [comment]
- [x] NFS series, Juiced 2, Ridge Racer Drift  — **fixed (0.82.3)**
- [ ] Ridge Racer, SpeedChaser 3D, SRW3D, The Sims Pool 3D — **unfixed, still same problem**

**Comment by ptnnx** [comment]
#68
