### ISSUE TITLE
PAC-MAN Kart 3D Rendering Glitch

### ISSUE THREAD

**Issue by EXsampleProject** [woesss/JL-Mod#56]
Build version: 0.82.2

Game version: 1.0.1

Game resolution: 240x320

Device model: VIVO Y12

Android version: 11

Description of the issue:
3D Rendering Issue, the game working correctly in the version 0.81 without any problem, but after update to latest 0.82.2 the game is working, but the render is broken, lots of isturbing black pixel dots. 

------------------------------------
This
Version Latest 0.82.2
![Screenshot_20220617_095555](https://user-images.githubusercontent.com/42617249/174217317-cf110417-db14-4cd8-bf48-ad67b59b1aec.jpg)

------------------------------------
This
Version 0.81 Old
![Screenshot_20220617_100032](https://user-images.githubusercontent.com/42617249/174217451-4c8993b7-8f80-4214-b17d-e7a81ae665e3.jpg)

**Comment by woesss** [comment]
Sould be fixed in 0.83

**Comment by EXsampleProject** [comment]
Good 👍 Thanks
![Screenshot_20220625_154500](https://user-images.githubusercontent.com/42617249/175765906-91fc1bfd-3d97-4919-b914-300efcef293c.jpg)
