### ISSUE TITLE
Mascot Capsule games runs very slow

### ISSUE THREAD

**Issue by Raypuia** [woesss/JL-Mod#6]
Emulator version: b071+MC_b096 

Game version: Most Mascot Capsule games

Game resolution: 240x320

Device: Samsung Galaxy Note (GT-N7000)

Android version: Android 4.1 Jelly Bean

Description of the issue: Most of the games that use Mascot Capsule runs considerably worse that M3G ones, the only one i find it runs fine is NitroStreet Racing 3D, when the others (Fishlabs games for example) struggles with just 10fps or less

**Comment by woesss** [comment]
The implementation is in Java, and this imposes some limitations in terms of optimization. I have not yet found a way to improve performance. Most likely, only code porting to native (C/C++) can help, but I'm not ready for this yet.

**Comment by Atamg1994** [comment]
> Description of the issue: Most of the games that use Mascot Capsule runs considerably worse that M3G ones, the only one i find it runs fine is NitroStreet Racing 3D, when the others (Fishlabs games for example) struggles with just 10fps or less

-
check this post, maybe it will help you?
Install the mod version from this post.

This will speed up the game (you'll need to reinstall the game itself using the mod).

It will become very fast. If it's too fast, limit the FPS in the settings.

https://github.com/woesss/JL-Mod/issues/130
