### ISSUE TITLE
Game failed to Open and Crashes

### ISSUE THREAD

**Issue by RonJay55** [woesss/JL-Mod#7]
**Build version:**
b071+MC_b096
**Game version:**
Any
**Game resolution:**
Any
**Device model:**
Oppo A5s
**Android version:**
8.1.0
**Description of the issue:**
Why the Java Game doesn't open and crashes? while I'm using the latest version? I played Diamond Rush, but nothing happen it started to blank. and I don't see the keyboard then i tap it and crashes. My solution is tried to reinstalled for Previous version and will be worked. Is there for problem for Latest Version to this error?
Anyway thanks for the J2me mod. :)
![Screenshot_2020-06-26-17-45-59-35](https://user-images.githubusercontent.com/67462068/85844533-75c54100-b7d5-11ea-8810-b2037110a35a.jpg)
![Screenshot_2020-06-26-17-46-06-49](https://user-images.githubusercontent.com/67462068/85844585-8bd30180-b7d5-11ea-8ec1-a07ef0eb86f4.jpg)

**Comment by Dezz34** [comment]
Same Issue. But i used for Previous Version, it be will worked for playing Java Games.

**Comment by woesss** [comment]
In this version, a problem was found in the graphic modes "Software" and "HW Acceleration (Surface)". I'm working on it. Try the OpenGL ES mode - no one has complained about it yet and I plan to abandon other modes.

**Comment by enomat** [comment]
I wanted to report the same thing, but before reporting it I waited a few days assuming a new version will be released soon with a quick fix (such as the b071+MC_b096 version was released after the b070+MC_b096).

**Comment by RonJay55** [comment]
> In this version, a problem was found in the graphic modes "Software" and "HW Acceleration (Surface)". I'm working on it. Try the OpenGL ES mode - no one has complained about it yet and I plan to abandon other modes.

Oh thanks..... i thought it was a bug 💀

**Comment by RonJay55** [comment]
> In this version, a problem was found in the graphic modes "Software" and "HW Acceleration (Surface)". I'm working on it. Try the OpenGL ES mode - no one has complained about it yet and I plan to abandon other modes.

i tried OpenGL ES Mode but still Crashed 💀
![Screenshot_2020-06-27-00-30-50-35](https://user-images.githubusercontent.com/67462068/85879787-8691a900-b80d-11ea-97d3-70f7d9edea23.jpg)
![Screenshot_2020-06-27-00-30-59-47](https://user-images.githubusercontent.com/67462068/85879796-8beef380-b80d-11ea-83f9-c54b2a005d4b.jpg)

**Comment by woesss** [comment]
After the fall, click `menu->save log` and send me the `log.txt` file from the emulator working directory

**Comment by RonJay55** [comment]
> After the fall, click `menu->save log` and send me the `log.txt` file from the emulator working directory

https://drive.google.com/file/d/1AKt60UrtsyKBy2bMySgxhebpfgprwg2r/view?usp=drivesdk
I don't know how to upload the file

**Comment by woesss** [comment]
> idk how to upload the file :-\  

read the line at the bottom of the comment edit box   

Something did not work with the log - it is almost empty. Try again.

**Comment by RonJay55** [comment]
> > idk how to upload the file :-\
> 
> read the line at the bottom of the comment edit box
> 
> Something did not work with the log - it is almost empty. Try again.

i did for there's a save log and upload it.  I don't get it, what is really is....

**Comment by woesss** [comment]
Just do it again.  
Because there is no necessary information in this log.  
Run the game in OpenGL ES mode and save the log after an error.  
In other modes it is not necessary - their problem is already known.

**Comment by RonJay55** [comment]
> Just do it again.
> Because there is no necessary information in this log.
> Run the game in OpenGL ES mode and save the log after an error.
> In other modes it is not necessary - their problem is already known.

i can't get it because of automatically crash on OpenGL ES Mode :(

**Comment by woesss** [comment]
Try next build

**Comment by RonJay55** [comment]
> Try next build

Update: It actually fixed a issue and worked for me! Thanks for Next Bulid! 💖

**Comment by enomat** [comment]
The b072+MC_b096 version is still not fixed.

Tested on LG V20, Android 8:
Graphics mode:
-software: no graphics, but sound is playing
-OpenGL ES: working
-window: working
-surface: no graphics, but sound is playing

Tested on Samsung Galaxy S3 Neo, Android 4.4.4:
Graphics mode:
-software: working
-OpenGL ES: working
-window: working
(surface: option is not available)

**Comment by enomat** [comment]
Tested `b072+MC_b096` and `b070+MC_b096`, both have the same problems on Samsung Galaxy A8 2018, Android 8:

Graphics mode:
- software: no graphics, but sound is playing
- OpenGL ES: working
- window: working
- surface: no graphics, but sound is playing

The b069+MC_b095 works perfectly with both enabled and disabled HW acceleration.

**Comment by woesss** [comment]
@enomat, thanks for the tests.
If possible, I will fix all the modes.
But, as I wrote above, OpenGL ES is a priority, I left others only because OpenGL ES was not used before and I'm not sure that it works for everyone.
