### ISSUE TITLE
Implement SAF for game storage

### ISSUE THREAD

**Issue by DavidAriyan** [woesss/JL-Mod#71]
You've made a really great mod of J2meloader. 
Thanks for this.
I just want this emulator to use the SAF implementation of newer version of android. So we can put the game folder in any storage and any directory we want. Rather than just use internal storage to store the games.
The original J2MELOADER now can stores the games in any directory in any storage like sdcard. But it save the data to it's own app folder inside the android -> data. I think it should implement import & export feature like the one in dolphin emu, in preparation for android 13.
But i hope this 3d mod version should use SAF instead so we can use external storage.

I also had an idea to change the app name of this mod to J2MELOADER 3D. What do you think?

**Comment by ptnnx** [comment]
J2ME Loader can support Mascot Capsule 3D!
J2ME Loader = JL-Mod
I think only different name and few words!

**Comment by DavidAriyan** [comment]
> J2ME Loader can support Mascot Capsule 3D! J2ME Loader = JL-Mod I think only different name and few words!

No it didn't fully supported it.
This mod by woess is the one with more support of 3d mascot games and have advanced compression game support. It's also still support games on the internal SD not just in the app data.
What we need now is the implemented of SAF, so we can store our games on an external storage like SD card. Many emulators has been implemented this SAF system.

**Comment by stevenfelix505** [comment]
@DavidAriyan External storage access has been implemented in version [0.84](https://github.com/woesss/JL-Mod/releases/tag/0.84) and [0.84.1](https://github.com/woesss/JL-Mod/releases/tag/0.84.1)

**Comment by DavidAriyan** [comment]
As SAF has been successfully implemented by the dev I'm gonna close this issue. I forgot to close this earlier.
Big thanks to dear developer, Woess. Happy new year for us all.
