### ISSUE TITLE
No sfx sound, only music sounds appear

### ISSUE THREAD

**Issue by Wolfgang1999** [woesss/JL-Mod#79]
**Build version:**
0.85.2 and 0.86 alpha
**Game version:**
1.3.1
**Game resolution:**
240x320
**Device model:**
Redmi 5a
**Android version:**
7.1.2
**Description of the issue:**
There is no sfx only music sounds appear and this happens in all the games I own for example ghost recon FS

**Comment by woesss** [comment]
Is SFX enabled in the game itself?  
I don’t have such a device, and I don’t see such problems on mine.  
Save the log immediately after starting the game and the moment when the first sound should be played and send me this log - perhaps this will help clarify the situation.

**Comment by Wolfgang1999** [comment]
> Is SFX enabled in the game itself? I don’t have such a device, and I don’t see such problems on mine. Save the log immediately after starting the game and the moment when the first sound should be played and send me this log - perhaps this will help clarify the situation.

[log.txt](https://github.com/woesss/JL-Mod/files/13699960/log.txt)

**Comment by Wolfgang1999** [comment]
And yes all sound and sfx is enabled, I've also tried on original JL and I don't get this issue in there

**Comment by woesss** [comment]
Thank you, I think I understand what the problem is.
It should now work in "Development Build".

**Comment by Wolfgang1999** [comment]
Ah great Thankyou
