### ISSUE TITLE
Graphics bug since the b070+MC_b096 version

### ISSUE THREAD

**Issue by enomat** [woesss/JL-Mod#8]
**Build version:**
b070+MC_b096

**Game version:**
Super Real Tennis, download here:
https://www.mobiles24.co/downloads/s/61685-m374-super_real_tennis

**Game resolution:**
176x220

**Tested on these phones:**

- LG V20, Android 8.0.0
- Sony Xperia L, Android 4.1.2
- Samsung Galaxy S3 Neo, Android 4.4.4

**Description of the issue:**
Since the b070+MC_b096 version the bottom part of the game is not visible where the "Go to the Game menu" text should be visible in the menu. b069+MC_b095 version works perfectly.

**b069+MC_b095:**
<img src="https://user-images.githubusercontent.com/12612250/85952548-527fca80-b96a-11ea-8f08-bbab7eab10c8.png" height="500px">

**b070+MC_b096:**
<img src="https://user-images.githubusercontent.com/12612250/85952555-6297aa00-b96a-11ea-92b1-ce3dfbab53ae.png" height="500px">

**Comment by woesss** [comment]
Try to enable the "Force fullscreen" option - this should help.
I will fix it as soon as I find the reason.

**Comment by woesss** [comment]
fixed
