### ISSUE TITLE
Mafia 2 Mobile | Rally Master Pro 3D | Soundbanks

### ISSUE THREAD

**Issue by NEStalgia-BR** [woesss/JL-Mod#82]
**Build version:**
JL-Mod_0.85.2-armeabi-v7a

**Game version:**
Mafia 2 Mobile 1.0.0
Rally Master Pro 1.0
Nokia Lloyd Bank 05.05

**Game resolution:**
Mafia 2 Mobile All resolutions
Rally Master Pro All resolutions

**Device model:**
LG K40s

**Android version:**
10

**Description of the issue:**

Hey there! I come here to report 3 problems:

MAFIA 2: one of my favorite Java games, Mafia 2 Mobile, is not running correctly on the JL-Mod or J2ME Loader Emu. The game suffers from slowdowns when displaying the stage titles and when removing the dark edges of dialogue, even crashing completely. I recorded a video showing the bug: 
https://github.com/woesss/JL-Mod/assets/143229376/1f016311-0080-4f8c-8f3d-533a8be3d59f

RALLY MASTER PRO: works correctly in J2ME Loader, but it crashes and quits when you choose a game mode, even with the Mascot 3D Capsule. Another bug is that the game has a default "High" sound volume option, but in JL-Mod the sound starts low and only returns to normal when changing the sound settings in the game. Furthermore, if you turn off the volume and turn it on "High", the game exits. I recorded 2 videos to show:

In-game crash:
https://github.com/woesss/JL-Mod/assets/143229376/b604f22c-8358-4278-8393-afe565c95f13

Low volume (it appears to only affect the game's .mid files, not the other sound extensions in the game files, like .wav):
https://github.com/woesss/JL-Mod/assets/143229376/5ae13c32-d5ed-4f73-ba01-34d603d2f69e

None of these problems happen with Rally Master Pro in J2ME Loader.

SOUNDBANKS: thank you very much for adding this feature! I recently found out about soundfonts and discovered the best Java soundfont file, used on Asha cell phones, with the best instrument quality, better than the Nokia S40 soundfont; the Nokia Lloyd Bank .sf2, attached in the .zip file below (included with the Series 40 5th edition FP1 GM soundfont, which is the second best)

[BestSoundFonts.zip](https://github.com/woesss/JL-Mod/files/14174587/BestSoundFonts.zip)

Android's default soundfont, SONiVOX EAS, is terrible, much lower in quality than Nokia old devices. In fact, Android's EAS synth has never been present on J2ME mobile devices, so there is no point in using it as the default in the emulator! For this reason, I ask you to add the best soundfont, Lloyd Bank, as the DEFAULT of the emulator, as it was used on real J2ME cell phones.

In the past, I've used a Nokia Asha 310, Nokia Asha 302, Nokia C2-05 and 2 or 3 other J2ME devices. So that suggestion comes from someone who has had experience with Java sound.

That's it, thank you!

*All video examples have sound quality from Lloyd Bank SoundFont, so note the quality! ;)

**Comment by NEStalgia-BR** [comment]
@woesss

**Comment by woesss** [comment]
Mafia can be fixed by setting the FPS limit within reason (most phones do not produce more than 60 FPS)
