### ISSUE TITLE
Better Sound Quality and Customization

### ISSUE THREAD

**Issue by NEStalgia-BR** [woesss/JL-Mod#83]
Hi, don't forget to also read my issue below this one about Mafia 2 and other questions. It'll be worth it.

Please add Nokia Lloyd Bank font as app default as Android default EAS synthesizer was never present on old J2ME devices. The Nokia font I mentioned was used in real Nokia Asha cell phones and has the best quality, or certainly one of the best. Here is the .zip file with it, with also the font for the s40 series, the second best: [BestSoundFonts.zip](https://github.com/woesss/JL-Mod/files/14175028/BestSoundFonts.zip)

I noticed that JL-Mod's soundfont Playback, in some games, plays some instruments loud and others low (That's cuz I have a Nokia Asha 302 kept at home that uses Lloyd Bank soundfont and I can compare the sounds, but this is also easy to notice in the emulator when an instrument is too loud). Please fix it. The best MIDI playback I found was from Volcano's mobile MIDI Player, which also supports SoundFonts:

![Screenshot_20240206-011212~2](https://github.com/woesss/JL-Mod/assets/143229376/01b0a343-7dda-43fb-a258-0020a598851e)

👆 It'd be really great to copy its source code over sounfonts and add it to the JL-Mod and J2ME Loader.

The Soundbanks option urgently needs to be ported to J2ME Loader! This [directory](http://onj3.andrelouis.com/phonetones/Software%20and%20Soundbanks/Soundbanks/Nokia/Soundfonts%20(SF2)/) has some soundfonts that can be built into the emulator, so that people can also choose the source they want.

For those who didn't quite understand, in this post you can read a little about how music works on J2ME devices: #27 

Finally, I made a comparison between the Android and Nokia Soundfont with 3 tunes. Find out for yourself which one sounds better: [Android_vs_Nokia_MIDI.zip](https://github.com/woesss/JL-Mod/files/14175792/Android_vs_Nokia_MIDI.zip)

Thanks for reading!

**Comment by NEStalgia-BR** [comment]
@woesss

**Comment by woesss** [comment]
I don't want to fill the emulator with resources that can be downloaded separately and that are not required to work. Everyone can download exactly what they need. But what is packed into the emulator cannot be deleted and the whole heap of unnecessary junk will take up space in memory without any benefit.

**Comment by SmithGoll** [comment]
> I noticed that JL-Mod's soundfont Playback, in some games, plays some instruments loud and others low (That's cuz I have a Nokia Asha 302 kept at home that uses Lloyd Bank soundfont and I can compare the sounds, but this is also easy to notice in the emulator when an instrument is too loud). Please fix it.

I think you should try the original Nokia Lloyd Bank from [here](http://onj3.andrelouis.com/phonetones/Software%20and%20Soundbanks/Soundbanks/Nokia/Beatnik%20(DLS,%20HSB)/Lloyd%20Bank.dls)

This DLS soundbank is actually extract from Nokia S40 phone's firmware, I have tested it and it really sounds better than tinysoundfont sound, please give it a try :-)
