### ISSUE TITLE
Russian message popping up

### ISSUE THREAD

**Issue by iplayfastandfurious** [woesss/JL-Mod#84]
<img width="960" alt="Screenshot 2024-02-22 095016" src="https://github.com/woesss/JL-Mod/assets/153218731/cd1d130c-3f83-4294-b91c-499bd7b43bdd"> when playing fast and furious adrenaline java, I got this russian message popping up and i'm not sure what it means

**Comment by woesss** [comment]
This means that the trial time has ended and you are offered to pay for the purchase of the game via SMS or enter the activation code received in the response SMS. By the way, the emulator does not support sending SMS. And the store probably no longer exists.

**Comment by iplayfastandfurious** [comment]
Trial time?
