### ISSUE TITLE
The problem is related to the SMS crack game 

### ISSUE THREAD

**Issue by Phalam754** [woesss/JL-Mod#88]
With game crack by SMS. No items are added when performing the SMS sending operation Looks like SMS is not going through.Link game test:https://giaitri321.pro/game-offline/gamehay/2/vuong-quoc-sung-vat-cau-vong/

**Comment by woesss** [comment]
Has this ever worked in another emulator or phone?
It would be a good idea to compare the hacked version with the original to understand what was changed and why it doesn't work.

**Comment by Phalam754** [comment]
They don't work even in the original j2me loader.But the first version caused the app to crash when sending SMS. Newer versions no longer crash.Instead, there is a notification of failure to send SMS

**Comment by Phalam754** [comment]
It's hard to find an app that hasn't had its SMS cracked yet. Here I have an application whose SMS status is unknown.But fortunately there are items added when sending SMS.The SMS interface and operations are 100% the same.Only the regional language differs.
Link: https://drive.google.com/file/d/197uSzGstdtS2QhaHkHfH6UDmSBSw13gE/view?usp=drivesdk

**Comment by woesss** [comment]
The problem is in the settings: the game somehow calculates the compliance of the IMEI code with the platform. I simply replaced Nokia with Sony Ericsson in the system property   
`microedition.platform: SonyEricssonK800`   
After changing the platform, you will have to start the game again - the continuation freezes.

**Comment by Phalam754** [comment]
Thank you. After I edited the code like you.The sms message has been sent successfully

**Comment by Phalam754** [comment]
Perhaps you should add another note to fix this problem.Many people encounter the same SMS situation as me.

**Comment by Phalam754** [comment]
After testing I found a few games that worked well.The application still has SMS errors. But the solution is correct
