### ISSUE TITLE
Fix Button Overlap on Widescreen Phones

### ISSUE THREAD

**Issue by stevenfelix505** [woesss/JL-Mod#9]
Screenshot from latest version of original J2ME Loader:
![Screenshot_20200630-100810_J2ME Loader](https://user-images.githubusercontent.com/57618009/86079251-4c006880-baba-11ea-911a-6268bb26e778.jpg)
—————
Screenshot from latest version of JL-Mod:
![Screenshot_20200630-100743_JL-Mod](https://user-images.githubusercontent.com/57618009/86079386-95e94e80-baba-11ea-8f98-a579f09c5513.jpg)

**Comment by stevenfelix505** [comment]
This issue has been closed due to no reply from @woesss

**Comment by woesss** [comment]
I have not found an adequate solution. The virtual keyboard was originally designed so that now resizing will be reflected in all layouts (including manually configured ones - users will have to fix them again)

**Comment by stevenfelix505** [comment]
@woesss 
Yes, but can you fix the button overlap as @nikita36078 already did in the original J2ME-Loader?
