### ISSUE TITLE
Gangstar 2 - Portrait Bug (5800 Xpressmusic)

### ISSUE THREAD

**Issue by GamingDucking** [woesss/JL-Mod#90]
**Build version:**
0.86-240426-794f0de
**Game version:**
1.0.0
**Game resolution:**
360x640
**Device model:**
Huawei P40 Lite E
**Android version:**
10
**Description of the issue:**
When I installed the game, it only shows "This game is not supported in portrait mode". I will give both log and screenshots.
![Screenshot_20240515_194837_ru woesss j2meloader](https://github.com/woesss/JL-Mod/assets/90236481/cf571720-c861-4586-9257-3aaa7ec366ad)
[log.txt](https://github.com/woesss/JL-Mod/files/15324582/log.txt)

**Comment by woesss** [comment]
360x640 – portrait resolution.
640x360 – landscape.
You need to swap the sizes in the settings
