### ISSUE TITLE
Block'D portrait bug (Nokia E90) 

### ISSUE THREAD

**Issue by GamingDucking** [woesss/JL-Mod#92]
**Build version:**
0.86-240426-694eb8f
**Game version:**
4.17.44
**Game resolution:**
800x320
**Device model:**
Huawei P40 Lite E
**Android version:**
Android 10
**Description of the issue:**
The same issue as #90, but this time changing it to 352x800 doesn't seem to work.
![Screenshot_20240520_194240](https://github.com/woesss/JL-Mod/assets/90236481/744f2ada-2d22-4744-831d-1b4e3b5a0b60)
[log.txt](https://github.com/woesss/JL-Mod/files/15379770/log.txt)

**Comment by woesss** [comment]
For some reason, sites with games can’t open for me - I can’t download it.  
But the resolution is stated there as 800x352, not 800x320 - maybe this is the problem?

**Comment by GamingDucking** [comment]
Yeah, did made a mistake while explaining the resolution. Tryed that, still nothing.

**Comment by woesss** [comment]
This game only runs in 240x320 resolution.
