### ISSUE TITLE
zip

### ISSUE THREAD

**Issue by soundsnow** [woesss/JL-Mod#96]
AOSP's Files app allow me to install 7z and zip with JL

can you add 7z and zip extensions. Because I uploaded a zip to your GH issue, GH doesn't allow me to upload jar

We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by woesss** [comment]
I did not understand anything. Try wording the description differently.
