### ISSUE TITLE
fix 4pda URL and 中文 and português for JL Mod and JL

### ISSUE THREAD

**Issue by soundsnow** [woesss/JL-Mod#99]
tested
http://4pda.ru/forum/index.php?showtopic=824201
Redirect and CloudFlare page
https://4pda.to/forum/index.php?showtopic=824201

and where's JL Mod? no JL Mod on that page

Settings - Language: 中文 and 中文
They're same? It's bug? One of them is unavailable?
Top 中文 to Bottom 中文
Bottom 中文 to Bottom 中文
And where's Taiwanese 中文? only Chinese 中文?

português is same like 中文
Settings - Language: português and português

**Comment by woesss** [comment]
I am not the developer of J2ME Loader and have nothing to do with its topic on 4pda.  
The names of the languages ​​have been corrected.

**Comment by woesss** [comment]
Try to describe the problem in a way that is understandable.  
The languages ​​are now corrected.  
I still don’t understand what you want from me in the context of 4pda...
